### ISSUE TITLE
Pripraviť Návrh

### ISSUE THREAD

**Issue by caawww** [TIS2023-FMFI/pracovne-instrukcie#11]
Vytvoriť všetky časti návrhu:

- [x] #6
- [x] #12
- [x] #13
- [x] #14
- [x] #16
- [x] #18 
- [x] #19 
- [x] #20 
- [x] #21
- [x] #22 

začať písať návrh

**Comment by veronika164** [comment]
aktívne sa na ňom pracuje v online word-documente
