### ISSUE TITLE
A: podrobná špecifikácia vonkajších interfejsov

### ISSUE THREAD

**Issue by caawww** [TIS2023-FMFI/pracovne-instrukcie#12]
ak aplikácia komunikuje s inými aplikáciami, súbormi, zariadeniami - tieto musia byť jasne a podrobne definované

**Comment by caawww** [comment]
- samotné čítanie inštrukcií (DOCX, PDF)
- #6
- otvorenie inštrukcie (v čom?, ako?)

**Comment by veronika164** [comment]
napísané (kľudne opravte), nie je mi jasné: 
- kde treba opísať tie e-mailové notifikácie a či vôbec treba? 
- bude naša aplikácia komunikovať s nejakými inými zariadeniami? 

Edit 17:43 
Teraz vidím že tie maily sú opísané nižšie

**Comment by veronika164** [comment]
vyriešené, napísané

**Comment by caawww** [comment]
dopísať a upresniť ešte zvyšok v Návrhu podľa pripomienok v ňom

**Comment by caawww** [comment]
dopísané v dokumente
