### ISSUE TITLE
C: návrh používateľského rozhrania

### ISSUE THREAD

**Issue by caawww** [TIS2023-FMFI/pracovne-instrukcie#14]
nakreslené a popísané všetky dialógy, okná a stránky, ktorými aplikácia komunikuje s používateľom - túto časť treba konzultovať so zadávateľom

**Comment by caawww** [comment]
Používateľ:
- prihlasovacie okno (zadanie 4-miestneho zamestnaneckého kódu)
- vyhľadávací riadok, pod ním budú inštrukcie (prehľadávať až po zadaní "kľúčového slova" alebo priebežne počas písania)
- ?okno zobrazenia PDF alebo zobrazenie v aplikácii tretej strany

Admin:
- okno s inštrukciami, ktoré sú (pravdepodobne) zoradené podľa konca platnosti validácii (prvé tie, čo skôr končia)
- nejaký interfejs na validovanie inštrukcie (posunúť termín, nahrať?, nastavenie frekvencie validácií, nastavenie posielania e-mailu?)
- ?zobrazenie výkazov za posledné mesiace, histogram
- ?pripisovanie zamestnancov do databázy pre umožnenie prístupu do systému (aj odstránenie?)

**Comment by MatejBudos** [comment]
[GUI.zip](https://github.com/TIS2023-FMFI/pracovne-instrukcie/files/13444815/GUI.zip)

**Comment by caawww** [comment]
Prejsť si návrh UI so zadávateľom (pravdepodobne na online stretnutí)

**Comment by caawww** [comment]
Návrh bol schválený zadávateľom
