### ISSUE TITLE
Katalog poziadaviek

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2023-FMFI/pracovne-instrukcie#17]
Vytvorit KP, dat ho skontrolovat cviciacemu, a po jeho schvaleni cviciacim
poslat na validaciu zadavatelom a potom este zohladnit ich pripomienky.

**Comment by pavelpetrovic** [comment]
[Katalog_Poziadaviek_s_postrehmi.docx](https://github.com/TIS2023-FMFI/pracovne-instrukcie/files/13039592/Katalog_Poziadaviek_s_postrehmi.docx)

**Comment by pavelpetrovic** [comment]
* validacia instrukcii - ci ide o novy zaznam, alebo stale ten isty zaznam len so zmenenym suborom, ake to ma vsetky dosledky? napr. z historii otvori predtym prehliadany - zobrazi sa posledna platna alebo tu verziu ktoru prezeral? ostavavaju evidovane aj predch. dokumenty? daju sa nejak pozerat? moze si pozerat poslednu platnu cez historiu aj ked uz neplati?  => prosim lepsie popisat validaciu na konci 2.2
* zvazte/zistite, ci by nebolo pre nich prijatelne riesenie, aby mohol aktualizovat instrukcie priamo z kancelarie, napr. cez sharepoint, google drive, dropbox, alebo idealne ak by sa dal na ich sieti na nejakom pocitaci pustit sftp server
    https://winscp.net/eng/docs/guide_windows_openssh_server
   - je to optional cast normalneho windows 10,11 takze toto by mohli v pohode zvladnut.
  ak by to bol sharepoint, treba najst vhodne API na download dokumentov z neho, existuju napr. REST API na toto,
   ale bolo by to treba odskusat a ci to zvladne vsetky security prekazky po ceste (autentifikacia)
* možnost’ nastavit’ => moznost zmenit (2.2)
* aktualizujte po konzultacii so zadavatelom technologiu android uvedenu v KP
* dotykovy displej napr. https://www.alza.sk/43-iiyama-prolite-t4362as-b1-d7714727.htm
* male PC napr. https://www.alza.sk/hp-pro-400-g9-cierny-d7412961.htm  (+linux, pripadne windows ak maju firemnu licenciu)
* pripadne este raz zistite, ci nechcu aj moznost citacky, je to lacne riesenie, napr.
    https://www.drotik-elektro.sk/arduino-platforma/954-usb-rfid-citacka-125khz.html
  a mohli by sme im k tomu spravit aj primontovatelnu krabicku vytlacenu z 3D tlaciarne

**Comment by pavelpetrovic** [comment]
este mi napadlo, ze ci admin nechce pozriet, ktore instrukcie si ten-ktory zamestnanec cital.
zamestnanec si to vie pozriet, takze sa to eviduje a ci tento pohlad pre vybraneho zamestnanca
rovno neumoznit aj adminovi.

**Comment by veronika164** [comment]
schválený cvičiacim, odoslaný na kontrolu pre zadávateľa

**Comment by caawww** [comment]
Katalóg požiadaviek bol schválený zadávateľom
