### ISSUE TITLE
UML class diagram

### ISSUE THREAD

**Issue by caawww** [TIS2023-FMFI/pracovne-instrukcie#18]
Vytvoriť zrozumiteľný UML class diagram.

**Comment by veronika164** [comment]
vytvorený, je v návrhu a čaká na kontorlu

**Comment by caawww** [comment]
UML Class diagram je potrebné prerobiť podľa schválenej a dohodnutej štruktúry súborov, ktoré budú priamo v kóde..


_Prosim pomenovavat triedy tak ako budu v kode. Zoznam pouzivatelov by snad dal ulozit ako List<> niekam… potrebuje samostatnu triedu?
Ako prvotna ukazka je to mile, zacnite tym, ze budete pisat prazdne hlavicky tried a metod rovno v kode a potom z toho vygenerujte triedny diagram`_
\- p. Petrovič
