### ISSUE TITLE
State Diagram

### ISSUE THREAD

**Issue by caawww** [TIS2023-FMFI/pracovne-instrukcie#20]

**Comment by Brosk1248** [comment]
pridana verzia do dokumentu Navrh, prosim si feedback lebo asi to nie je moc dobre ale zaroven neviem ako inak

**Comment by caawww** [comment]
* Tú upravovaná by som dal na napr. "Nahrávaná novšia verzia" alebo niečo podobné.. keďže náš systém neponúka úpravu 
* možno z estetického hľadiska by som dal ten text zarovnaný na stred (v stavoch)
* možno ešte dať aj, že notifikuje admina o tom, že jej končí platnosť nejaký stav
A ešte prosím dať transparent background na obrázok

**Comment by Brosk1248** [comment]
hotovo, okrem "možno ešte dať aj, že notifikuje admina o tom, že jej končí platnosť nejaký stav", vzhľadom na to, že to nie je niečo, čo vykonáva inštrukcia
