### ISSUE TITLE
 Špecifikácia otázok na zadávateľa

### ISSUE THREAD

**Issue by caawww** [TIS2023-FMFI/pracovne-instrukcie#5]

**Comment by veronika164** [comment]
- webová aplikácia - technologia celkovo (android/pc)
- termin všetci alebo len admin
- každý si vyberá? každý vidí všetko?
- databáza používateľov?
- interface na validáciu? čo to je?
- Validator a admin to isté? Je nejaký schvaľovací proces?
- Tie notifikácie? Na mail či kam?
- čítačky - minulý projekt
- kto pridava používateľov? admin?
- zadám termín - nájdem najnovšiu verziu listu?
- formát - jednotný (jpg NIE)

**Comment by caawww** [comment]
Všetky otázky boli zodpovedané na osobnom stretnutí 17.10. Odpovede budú upresnené v katalógu požiadaviek.
