### ISSUE TITLE
Zápisnica zo stretnutia so zadávateľom (17.10)

### ISSUE THREAD

**Issue by caawww** [TIS2023-FMFI/pracovne-instrukcie#9]

**Comment by veronika164** [comment]
prosím vás o kontrolu - prípadné doplnenie
[zapisnica.pdf](https://github.com/TIS2023-FMFI/pracovne-instrukcie/files/13031620/zapisnica.pdf)
[zapisnica.docx](https://github.com/TIS2023-FMFI/pracovne-instrukcie/files/13031621/zapisnica.docx)

**Comment by veronika164** [comment]
mierne upravené

[zapisnica.docx](https://github.com/TIS2023-FMFI/pracovne-instrukcie/files/13031792/zapisnica.docx)

[zapisnica.pdf](https://github.com/TIS2023-FMFI/pracovne-instrukcie/files/13031793/zapisnica.pdf)

**Comment by caawww** [comment]
V predposlednom riadku, posledná veta o validácii nám vraveli, že väčšinou to je iba, že ju odklikneš aj na ďalší rok, občas to je iba, že tam nahráš novú (stará sa odstráni)

**Comment by veronika164** [comment]
lepšie takto? "Samotná pracovná inštrukcia má väčšinou dobu platnosti jeden rok a potom ide na validáciu (buď sa jej predĺži platnosť alebo sa pridá nová verzie inštrukcie a stará sa odstráni)."

**Comment by caawww** [comment]
Zapisnica je schvalena zadavatelom a na Wiki
